---
- hosts: localhost
  tasks:
    - name: Create logger_testing network
      docker_network:
        name: ltn
        ipam_options:
          subnet: '192.168.168.0/24'
          gateway: 192.168.168.1
          iprange: '192.168.168.0/24'

    - name: Create MySQL server
      docker_container:
        name: pl-mysql-single
        hostname: pl-mysql-single
        image: mysql:5.7
        restart: yes
        restart_policy: always
        tty: yes
        interactive: yes
        detach: yes
        exposed_ports:
          - 3036
        networks:
          - name: ltn
            ipv4_address: 192.168.168.3
        volumes:
          - ./data/mysql_single:/var/lib/mysql:rw
        env:
          MYSQL_DATABASE: "php_logger"
          MYSQL_USER: "logger"
          MYSQL_PASSWORD: "reggol"
          MYSQL_ROOT_PASSWORD: "YES"

    - name: Create apache php server
      docker_container: 
        name: php_logger
        image: php:7.2-apache
        hostname: php_logger
        restart: yes
        restart_policy: always
        detach: yes
        tty: yes
        interactive: yes
        published_ports:
          - 80:80
          - 443:443
        exposed_ports:
          - 80
          - 88
          - 443
        volumes:
          - ./laravel:/var/www:rw
        env:
           APACHE_DOCUMENT_ROOT: "/var/www/public"
        networks:
          - name: ltn
            ipv4_address: 192.168.168.2
        links:
          - "pl-mysql-single:myslq_single"

- hosts: php_logger
  gather_facts: no
  pre_tasks:
    - name: Install pdo_mysql chage document root extention
      raw: "{{ item }}"      
      with_items:
        - "docker-php-ext-install pdo_mysql"
        - "a2enmod rewrite"
        - "sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf"
        - "sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf"
        - 'cp "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"'
        - "/etc/init.d/apache2 restart"
